server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/Sidhu/IdeaProjects/microservices/git-localconfig-repo