apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api-gateway-app
  labels:
    app: cloud-api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-api-gateway-app
  template:
    metadata:
      labels:
        app: cloud-api-gateway-app
    spec:
      containers:
        - name: cloud-api-gateway-app
          image: sidhu/cloud-api-gateway:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-api-gateway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
  selector:
    app: cloud-api-gateway-app