apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-app
  labels:
    app: transaction-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service-app
  template:
    metadata:
      labels:
        app: transaction-service-app
    spec:
      containers:
        - name: transaction-service-app
          image: sidhu/transaction-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9003

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-svc
spec:
  ports:
    - targetPort: 9003
      port: 80
  selector:
    app: transaction-service-app